### ISSUE TITLE
Differentiation of `x ^ exp` for any exp < 1 gives NaN as result

### ISSUE THREAD

**Issue by RastislavMirek** [JuliaDiff/ReverseDiff.jl#176] opened 2021-05-03 00:30 UTC
The title has it. Trying to take gradient of `x -> x ^ 0.5`, where you can replace `0.5` by anything lesser than 1 will give you `NaN` for x.

This seems to me to be serious issue and rather unexpected behaviour, which means it is hard to find. As a temporary workaround until it is fixed I suggest using this function instead of `^` opearator:

```
rd_power(x::T1, exp::T2) where {T1 <: Real, T2 <: Real} = exp >= 1 ? x ^ exp : x ^ 2.0 / x ^ (2.0 - exp)
```

There is another issue that is dependent on this one (it's a special case for square root, this is more general): https://github.com/JuliaDiff/ReverseDiff.jl/issues/115

**Comment by devmotion** [comment] 2021-09-16 19:40
This works now:
```julia
julia> using ReverseDiff

julia> f(x) = first(x)^0.5
f (generic function with 1 method)

julia> ReverseDiff.gradient(f, [1.0])
1-element Vector{Float64}:
 0.5

julia> f(x) = first(x)^0.2
f (generic function with 1 method)

julia> ReverseDiff.gradient(f, [1.0])
1-element Vector{Float64}:
 0.2
```

I believe this was fixed in https://github.com/JuliaDiff/DiffRules.jl/pull/36.

**Comment by devmotion** [comment] 2021-12-16 22:04
Please reopen if the issue persists. I can't reproduce it anymore.

**Closed by devmotion** 2021-12-16 22:04 UTC
