### ISSUE TITLE
ReverseDiff.gradient incorrect with `if` and independent values.

### ISSUE THREAD

**Issue by NHDaly** [JuliaDiff/ReverseDiff.jl#82] opened 2017-07-08 05:29 UTC
I *think* this is a mistake (and maybe related to trying to do ReLu in #77?

When I tried to find the gradient for a function that sometimes doesn't use one of its inputs, instead of just that one input's gradient turning to 0, the gradients for all the elements of the input vector turned to 0:
```julia
julia> f(X) = sum([if x > 0; x else 0 end for x in X])
>> f (generic function with 1 method)

julia> ReverseDiff.gradient(f, [2,3,-1])
>> 3-element Array{Int64,1}:
 0
 0
 0

julia> ReverseDiff.gradient(f, [2,3,1])
>> 3-element Array{Int64,1}:
 1
 1
 1
```
I think this is a mistake? Only the third element in the returned array should be 0, since the other two variables *do* have a linear effect on the output of `f`.

Also, though, it currently does get this right for `max(0,x)`, which is another way to implement the same thing (I guess it considers `max(0,x)` inclusive for `x==0`):
```
julia> f(X) = sum([max(0, x) for x in X])
>> f (generic function with 1 method)

julia> ReverseDiff.gradient(f, [2,3,0])
>> 3-element Array{Int64,1}:
 1
 1
 1

julia> ReverseDiff.gradient(f, [2,3,-1])
>> 3-element Array{Int64,1}:
 1
 1
 0

```

**Comment by jrevels** [comment] 2017-07-09 14:54
I can't reproduce this...here's what I'm getting on my end (using ReverseDiff v0.1.4, the latest version):

```julia
julia> using ReverseDiff

julia> f(X) = sum([if x > 0; x else 0 end for x in X])
f (generic function with 1 method)

julia> ReverseDiff.gradient(f, [2,3,-1])
3-element Array{Int64,1}:
 1
 1
 0
```

I'll close this since it seems to be fixed on the latest ReverseDiff version, but please let me know if you encounter any issues with this.

**Comment by NHDaly** [comment] 2017-07-09 17:42
Huh, that is super weird. I just installed it again on a new machine, and I have `v0.1.4` as well. I also just ran `Pkg.update()`:

```julia
$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0 (2017-06-19 13:05 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Computing changes...
INFO: No packages to install, update or remove

julia> using ReverseDiff

julia> f(X) = sum([if x > 0; x else 0 end for x in X])
f (generic function with 1 method)

julia> ReverseDiff.gradient(f, [2,3,-1])
3-element Array{Int64,1}:
 0
 0
 0

julia>
```

Maybe it's something to do with my machine? I'm on a 2017 13" MacBook Pro, macOS 10.12.5.

Maybe it's something about my GPU? I don't think I have CUDA libraries b/c when I ran `Pkg.update()` last time Tensorflow complained about it:

```
INFO: Upgrading TensorFlow: v0.6.2 => v0.6.6
INFO: Building CUDAdrv
======================================================================[ ERROR: CUDAdrv ]======================================================================

LoadError: Could not find the CUDA driver library (specify the path to libcuda using the CUDA_DRIVER environment variable).
while loading /Users/nhdaly/.julia/v0.6/CUDAdrv/deps/build.jl, in expression starting on line 119

==============================================================================================================================================================
```

**Comment by NHDaly** [comment] 2017-07-09 17:43
Also, for more context:

```julia
julia> Pkg.installed()["ReverseDiff"]
v"0.1.4"

julia> Pkg.installed()["ForwardDiff"]
v"0.4.2"
```

**Comment by jrevels** [comment] 2017-07-09 18:16
It turns out I was still using Julia v0.6.0-rc3 (the final release candidate just before the v0.6.0 release), just updated to Julia v0.6.0 and now I can reproduce it. AFAICT, that means it was https://github.com/JuliaLang/julia/commit/e5e8be23bc571bb2612e0d419ef8e254d78ac3ff that introduced the bug here. I'll dig through that commit tomorrow. Thanks again for finding this!

> Maybe it's something about my GPU? I don't think I have CUDA libraries b/c when I ran Pkg.update() last time Tensorflow complained about it:

ReverseDiff doesn't automatically run anything on the GPU; it falls back to however array operations are defined on your input array type.

**Comment by NHDaly** [comment] 2017-07-17 00:28
cool, glad to help! good luck!

**Closed** 2017-07-31 18:21 UTC
